#include "Textures.h"

std::shared_ptr<SpriteSheet> Textures::m_mouseCrossHair;
std::shared_ptr<SpriteSheet> Textures::m_levelSelectBackground;
std::shared_ptr<SpriteSheet> Textures::m_enemyTerritoryHexSheet;
std::shared_ptr<SpriteSheet> Textures::m_levelSelect1;
std::shared_ptr<SpriteSheet> Textures::m_levelSelect2;
std::shared_ptr<SpriteSheet> Textures::m_levelSelect3;
std::shared_ptr<SpriteSheet> Textures::m_levelSelect4;
std::shared_ptr<SpriteSheet> Textures::m_levelSelect5;
std::shared_ptr<SpriteSheet> Textures::m_prebattleUIBackground;
std::shared_ptr<SpriteSheet> Textures::m_preBattleUIPlayButton;
std::shared_ptr<SpriteSheet> Textures::m_preBattleUIBackButton;
std::shared_ptr<SpriteSheet> Textures::m_playerSelectIconYellow; 
std::shared_ptr<SpriteSheet> Textures::m_playerSelectIconGreen;
std::shared_ptr<SpriteSheet> Textures::m_playerSelectIconRed;
std::shared_ptr<SpriteSheet> Textures::m_playerSelectIconBlue;
std::shared_ptr<SpriteSheet> Textures::m_playerSelectBackground;
std::shared_ptr<SpriteSheet> Textures::m_thing;
std::shared_ptr<SpriteSheet> Textures::m_hexTiles;
std::shared_ptr<SpriteSheet> Textures::m_afternoonHexTiles;
std::shared_ptr<SpriteSheet> Textures::m_eveningHexTiles;
std::shared_ptr<SpriteSheet> Textures::m_nightHexTiles;
std::shared_ptr<SpriteSheet> Textures::m_spawnHex;
std::shared_ptr<SpriteSheet> Textures::m_selectedHex;
std::shared_ptr<SpriteSheet> Textures::m_battleIcons;
std::shared_ptr<SpriteSheet> Textures::m_endPhaseButtons;
std::shared_ptr<SpriteSheet> Textures::m_pauseButton;
std::shared_ptr<SpriteSheet> Textures::m_chickenButton;
std::shared_ptr<SpriteSheet> Textures::m_pauseMenuBackground;
std::shared_ptr<SpriteSheet> Textures::m_resumeButton;
std::shared_ptr<SpriteSheet> Textures::m_quitButton;
std::shared_ptr<SpriteSheet> Textures::m_CompassBackGround;
std::shared_ptr<SpriteSheet> Textures::m_CompassPointer;
std::shared_ptr<SpriteSheet> Textures::m_WindArrow;
std::shared_ptr<SpriteSheet> Textures::m_activeFactionToken;
std::shared_ptr<SpriteSheet> Textures::m_postBattleBackground;
std::shared_ptr<SpriteSheet> Textures::m_doneButton;


std::shared_ptr<SpriteSheet> Textures::m_blueShipSideCannons; 
std::shared_ptr<SpriteSheet> Textures::m_blueShipBomb;
std::shared_ptr<SpriteSheet> Textures::m_blueShipMelee;
std::shared_ptr<SpriteSheet> Textures::m_blueShipSnipe;
std::shared_ptr<SpriteSheet> Textures::m_redShipSideCannons;
std::shared_ptr<SpriteSheet> Textures::m_redShipBomb;
std::shared_ptr<SpriteSheet> Textures::m_redShipMelee;
std::shared_ptr<SpriteSheet> Textures::m_redShipSnipe;
std::shared_ptr<SpriteSheet> Textures::m_greenShipSideCannons;
std::shared_ptr<SpriteSheet> Textures::m_greenShipBomb;
std::shared_ptr<SpriteSheet> Textures::m_greenShipMelee;
std::shared_ptr<SpriteSheet> Textures::m_greenShipSnipe;
std::shared_ptr<SpriteSheet> Textures::m_yellowShipSideCannons;
std::shared_ptr<SpriteSheet> Textures::m_yellowShipBomb;
std::shared_ptr<SpriteSheet> Textures::m_yellowShipMelee;
std::shared_ptr<SpriteSheet> Textures::m_yellowShipSnipe;

std::shared_ptr<SpriteSheet> Textures::m_background;
std::shared_ptr<SpriteSheet> Textures::m_explosionParticles;
std::shared_ptr<SpriteSheet> Textures::m_fireParticles;

std::shared_ptr<SpriteSheet> Textures::m_redSpawnHex;
std::shared_ptr<SpriteSheet> Textures::m_yellowSpawnHex;
std::shared_ptr<SpriteSheet> Textures::m_greenSpawnHex;
std::shared_ptr<SpriteSheet> Textures::m_blueSpawnHex;
